### ISSUE TITLE
LIAS and UNBIND buttons don't work

### ISSUE THREAD

**Issue by joeytyndale** [joeytyndale/JS_Injections#3]
Not sure why these buttons don't work. Need's investigation

**Comment by helloanurag** [comment]
@joeytyndale Also, can you rename the button from "Login in as user" to "Login as user".
Also, is it possible to host your JSON file in the cloud so that all the updates get pushed to everyone automatically?

**Comment by helloanurag** [comment]
I found an error which might be the issue that LIAS button is not working.
The ${admin.profileId} which you are using in the JSON, is failing to fetch the value. I am not sure if this is invalid now.
I was able to fetch the other values ${String(info.accountId)}, ${String(info.instanceData.key.id)}, ${String(info.profileData.profileIdentity)}. Can you check this var?

**Comment by joeytyndale** [comment]
@helloanurag  I think you're right about the admin. It seems like they've changed how the roles are returned. Used to be you could split the role by ',' and grab the [1] element. But the format is now: 
`urn:li:aclRole:(urn:li:aclProductGroup:EnterprisePlatform,LEARNING_ASSIGNMENTS_SUBJECT_MATTER_EXPERT)`
So I think we should change the .split() method here: https://github.com/joeytyndale/JS_Injections/blob/05a2f1384e6d525d6442f9e88c97440102f94c47/csp.js#L126
with a .indexOf() > -1 to see if `learningProductAdmin` is in the string at all

**Comment by joeytyndale** [comment]
Good news: The code change works
Bad news: That part was actually working before and apparently the "LiasForm" is to log in as full admin and has nothing to do with the actual LIAS. That's handled here: https://github.com/joeytyndale/JS_Injections/blob/05a2f1384e6d525d6442f9e88c97440102f94c47/csp.js#L189-L195

**Comment by joeytyndale** [comment]
I think the best way to move forward is to actually rebuild the LIAS and Unbind forms ourselves and attach our own even handlers to the custom buttons. Every other way seems too hit or miss.

**Comment by joeytyndale** [comment]
Added this new function that creates a userLiasForm:
https://github.com/joeytyndale/JS_Injections/blob/444efd5ea2b408ba71828f2537e8c5b621676851/csp.js#L182-L213

That's called by a simple onclick event here: 
https://github.com/joeytyndale/JS_Injections/blob/444efd5ea2b408ba71828f2537e8c5b621676851/csp.js#L373

**Comment by helloanurag** [comment]
Yes, the LIAS button works now! However, I haven't got a chance to use the Unbind button as all of my test profiles are for Profile Required accounts. I am not sure if you have already tested it already, but if I come across any such Unbind case, I will let you know the result.
Thanks for the amazing work!
